module:
  admin_toolbar: 0
  admin_toolbar_tools: 0
  automated_cron: 0
  better_exposed_filters: 0
  bg_image_formatter: 0
  big_pipe: 0
  block: 0
  block_class: 0
  block_content: 0
  block_visibility_groups: 0
  breakpoint: 0
  ckeditor: 0
  color: 0
  comment: 0
  config: 0
  config_update: 0
  consumers: 0
  contact: 0
  content_moderation: 0
  contextual: 0
  ctools: 0
  datetime: 0
  dblog: 0
  diff: 0
  dynamic_page_cache: 0
  editor: 0
  entity_browser: 0
  entity_browser_block: 0
  features: 0
  feeds: 0
  field: 0
  field_ui: 0
  file: 0
  filter: 0
  gavias_content_builder: 0
  gavias_hook_themer: 0
  gavias_sliderlayer: 0
  gavias_view: 0
  gaviasthemer: 0
  google_map_field: 0
  help: 0
  history: 0
  image: 0
  imce: 0
  inline_entity_form: 0
  jquery_ui: 0
  jquery_ui_datepicker: 0
  jquery_ui_slider: 0
  jquery_ui_touch_punch: 0
  jsonapi: 0
  layout_builder: 0
  layout_builder_restrictions: 0
  layout_builder_styles: 0
  layout_discovery: 0
  layout_library: 0
  lightning_api: 0
  lightning_banner_block: 0
  lightning_core: 0
  lightning_landing_page: 0
  lightning_layout: 0
  lightning_map_block: 0
  lightning_workflow: 0
  link: 0
  media: 0
  menu_link_content: 0
  menu_ui: 0
  metatag: 0
  moderation_dashboard: 0
  moderation_sidebar: 0
  node: 0
  openapi: 0
  openapi_jsonapi: 0
  openapi_ui: 0
  openapi_ui_redoc: 0
  openapi_ui_swagger: 0
  options: 0
  page_cache: 0
  page_manager: 0
  panels: 0
  path: 0
  path_alias: 0
  quickedit: 0
  rdf: 0
  redirect: 0
  redirect_404: 0
  schemata: 0
  schemata_json_schema: 0
  search: 0
  serialization: 0
  shortcut: 0
  simple_gmap: 0
  simple_oauth: 0
  simplenews: 0
  smtp: 0
  system: 0
  taxonomy: 0
  text: 0
  token: 0
  toolbar: 0
  tour: 0
  update: 0
  user: 0
  views_infinite_scroll: 0
  views_ui: 0
  webform: 0
  webform_ui: 0
  workflows: 0
  pathauto: 1
  views: 10
  standard: 1000
theme:
  claro: 0
  tp_basetheme: 0
profile: standard
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
