admin_toolbar: 2.3.0
admin_toolbar_tools: 2.3.0
automated_cron: 9.0.6
better_exposed_filters: 5.0.0-beta1
bg_image_formatter: 1.14.0
big_pipe: 9.0.6
block: 9.0.6
block_class: 1.2.0
block_content: 9.0.6
block_visibility_groups: 0.0.0
breakpoint: 9.0.6
ckeditor: 9.0.6
color: 9.0.6
comment: 9.0.6
config: 9.0.6
config_update: 1.7.0
consumers: 1.11.0
contact: 9.0.6
content_moderation: 9.0.6
contextual: 9.0.6
ctools: 3.4.0
datetime: 9.0.6
dblog: 9.0.6
diff: 1.0.0
dynamic_page_cache: 9.0.6
editor: 9.0.6
entity_browser: 2.5.0
entity_browser_block: 1.1.0
features: 3.11.0
feeds: 3.0.0-alpha9
field: 9.0.6
field_ui: 9.0.6
file: 9.0.6
filter: 9.0.6
gavias_content_builder: 9.x
gavias_hook_themer: 0.0.0
gavias_sliderlayer: 1.0.0
gavias_view: 0.0.0
gaviasthemer: 1.0.0
google_map_field: 1.14.0
help: 9.0.6
history: 9.0.6
image: 9.0.6
imce: 2.3.0
inline_entity_form: 1.0.0-rc7
jquery_ui: 1.4.0
jquery_ui_datepicker: 1.0.0
jquery_ui_slider: 1.1.0
jquery_ui_touch_punch: 1.0.0
jsonapi: 0.0.0
layout_builder: 9.0.6
layout_builder_restrictions: 2.7.0
layout_builder_styles: 1.0.0-beta2
layout_discovery: 9.0.6
layout_library: 1.0.0-beta2
lightning_api: 4.6.0
lightning_banner_block: 0.0.0
lightning_core: 5.3.0
lightning_landing_page: 0.0.0
lightning_layout: 0.0.0
lightning_map_block: 0.0.0
lightning_workflow: 3.15.0
link: 9.0.6
media: 9.0.6
menu_link_content: 9.0.6
menu_ui: 9.0.6
metatag: 1.14.0
moderated_content_bulk_publish: 2.0.0
moderation_dashboard: 1.0.0-beta2
moderation_sidebar: 1.4.0
node: 9.0.6
openapi: 2.0.0-rc3
openapi_jsonapi: 2.0.0-rc2
openapi_ui: 1.0.0-rc3
openapi_ui_redoc: 1.0.0-rc3
openapi_ui_swagger: 1.0.0-rc4
options: 9.0.6
page_cache: 9.0.6
page_manager: 4.0.0-beta6
panels: 4.6.0
path: 9.0.6
path_alias: 9.0.6
pathauto: 1.8.0
quickedit: 9.0.6
rdf: 9.0.6
redirect: 1.6.0
redirect_404: 1.6.0
schemata: 1.0.0-beta2
schemata_json_schema: 1.0.0-beta2
search: 9.0.6
serialization: 9.0.6
shortcut: 9.0.6
simple_gmap: 3.0.0
simple_oauth: 4.5.0
simplenews: 2.0.0-beta2
smtp: 1.0.0-rc4
standard: 9.0.6
system: 9.0.6
taxonomy: 9.0.6
text: 9.0.6
token: 1.7.0
toolbar: 9.0.6
tour: 9.0.6
update: 9.0.6
user: 9.0.6
views: 9.0.6
views_infinite_scroll: 1.7.0
views_ui: 9.0.6
webform: 6.0.0-alpha17
webform_ui: 6.0.0-alpha17
workflows: 9.0.6
